language: node_js

node_js:
  - "8.11"

notifications:
  email: false

cache:
  directories:
    - "node_modules"

env:
  global:
  - USER: "babtshe"
  - EMAIL: "babtshe@yandex.ru"


before_install:
  - openssl aes-256-cbc -K $encrypted_e0c9dc91188f_key -iv $encrypted_e0c9dc91188f_iv -in deploy_key.enc -out deploy_key -d
  - chmod 600 deploy_key
  - eval `ssh-agent -s`
  - ssh-add deploy_key

before_script:
  - npm install -g gulp-cli

script: gulp build

after_success:
  - git config --global user.email ${EMAIL}
  - git config --global user.name ${USER}
  - cd build
  - git init
  - git add .
  - git commit -m "Deploy by Travis"
  - git remote add production "git@github.com:babtshe/babtshe.github.io.git"
  - git push -f production master

